/**:
  ros__parameters:
    localization:
      type: diagnostic_aggregator/AnalyzerGroup
      path: localization
      analyzers:
        node_alive_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: node_alive_monitoring
          analyzers:
            topic_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: topic_status
              contains: [": localization_topic_status"]
              timeout: 1.0

        performance_monitoring:
          type: diagnostic_aggregator/AnalyzerGroup
          path: performance_monitoring
          analyzers:
            scan_matching_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: scan_matching_status
              contains: ["ndt_scan_matcher: scan_matching_status"]
              timeout: 1.0

            localization_stability:
              type: diagnostic_aggregator/GenericAnalyzer
              path: localization_stability
              contains: ["localization: pose_instability_detector"]
              timeout: 1.0

            sensor_fusion_status:
              type: diagnostic_aggregator/GenericAnalyzer
              path: sensor_fusion_status
              contains: ["localization: ekf_localizer"]
              timeout: 1.0
